sudo: false
services:
  - docker

language: cpp

# default values
os: linux
compiler: gcc

cache:
    directories:
      - $HOME/.cache

git:
    depth: 100500

env: >
    TEST_RUN_EXTRA_PARAMS="-j 1"

jobs:
    include:
      # Testing targets (just run tests on Debian Stretch or OS X).
      - name: "RelWithDebInfo build + test (Linux, gcc)"
        env: TARGET=test
      - name: "RelWithDebInfo build + test (Linux, clang)"
        env: TARGET=test
        compiler: clang
      - name: "Debug build + test + coverage (Linux, gcc)"
        env: TARGET=coverage
      # Power jobs
      - name: "RelWithDebInfo build + test (Linux, gcc)"
        env: TARGET=test
        arch: ppc64le
      - name: "RelWithDebInfo build + test (Linux, clang)"
        env: TARGET=test
        compiler: clang
        arch: ppc64le
      - name: "Debug build + test + coverage (Linux, gcc)"
        env: TARGET=coverage
        arch: ppc64le

script:
  - make -f .travis.mk ${TARGET}

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
