name: CI

on:
  push:
    branches: ['master']
  pull_request:

env:
  CI_MAKE: make -f .travis.mk

jobs:
  release_clang:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: ghcr.io/avtikhon/tarantool/testing/debian-stretch:latest

    steps:
      - uses: actions/checkout@v1
      - name: test
        env:
          CC: clang
          CXX: clang++
        run: ${CI_MAKE} test_debian_no_deps
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release_clang
          retention-days: 1000000
          path: test/var/artifacts
