name: CI

on:
  push:
    branches: ['master']
  pull_request:

env:
  CI_MAKE: make -f .travis.mk

jobs:
  release_asan_clang11:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: ghcr.io/avtikhon/tarantool/testing/debian-buster:latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: test
        run: ${CI_MAKE} test_asan_debian_no_deps
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release_asan_clang11
          retention-days: 1000000
          path: test/var/artifacts
